/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Thu Sep 21 10:24:28 2017. */

#include "test2.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t NestedMessage_fields[3] = {
    PB_FIELD(  1, MESSAGE , REPEATED, CALLBACK, FIRST, NestedMessage, variable, variable, &NestedMessage_Variable_fields),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, NestedMessage, timestamp, variable, 0),
    PB_LAST_FIELD
};

const pb_field_t NestedMessage_Variable_fields[4] = {
    PB_FIELD(  1, UINT32  , OPTIONAL, STATIC  , FIRST, NestedMessage_Variable, val, val, 0),
    PB_FIELD(  2, UINT32  , OPTIONAL, STATIC  , OTHER, NestedMessage_Variable, devid, val, 0),
    PB_FIELD(  3, UINT32  , OPTIONAL, STATIC  , OTHER, NestedMessage_Variable, varid, devid, 0),
    PB_LAST_FIELD
};


/* Check that field information fits in pb_field_t */
#if !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_32BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in 8 or 16 bit
 * field descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(NestedMessage, variable) < 65536), YOU_MUST_DEFINE_PB_FIELD_32BIT_FOR_MESSAGES_NestedMessage_NestedMessage_Variable)
#endif

#if !defined(PB_FIELD_16BIT) && !defined(PB_FIELD_32BIT)
/* If you get an error here, it means that you need to define PB_FIELD_16BIT
 * compile-time option. You can do that in pb.h or on compiler command line.
 * 
 * The reason you need to do this is that some of your messages contain tag
 * numbers or field sizes that are larger than what can fit in the default
 * 8 bit descriptors.
 */
PB_STATIC_ASSERT((pb_membersize(NestedMessage, variable) < 256), YOU_MUST_DEFINE_PB_FIELD_16BIT_FOR_MESSAGES_NestedMessage_NestedMessage_Variable)
#endif


/* @@protoc_insertion_point(eof) */
