/* Automatically generated nanopb constant definitions */
/* Generated by nanopb-0.3.6 at Thu Sep 21 10:24:27 2017. */

#include "test.pb.h"

/* @@protoc_insertion_point(includes) */
#if PB_PROTO_HEADER_VERSION != 30
#error Regenerate this file with the current version of nanopb generator.
#endif



const pb_field_t TestMessage_fields[27] = {
    PB_FIELD(  1, INT32   , REQUIRED, STATIC  , FIRST, TestMessage, a, a, 0),
    PB_FIELD(  2, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, b, a, 0),
    PB_FIELD(  3, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, c, b, 0),
    PB_FIELD(  4, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, d, c, 0),
    PB_FIELD(  5, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, e, d, 0),
    PB_FIELD(  6, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, f, e, 0),
    PB_FIELD(  7, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, g, f, 0),
    PB_FIELD(  8, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, h, g, 0),
    PB_FIELD(  9, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, i, h, 0),
    PB_FIELD( 10, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, j, i, 0),
    PB_FIELD( 11, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, k, j, 0),
    PB_FIELD( 12, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, l, k, 0),
    PB_FIELD( 13, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, m, l, 0),
    PB_FIELD( 14, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, n, m, 0),
    PB_FIELD( 15, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, o, n, 0),
    PB_FIELD( 16, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, p, o, 0),
    PB_FIELD( 17, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, q, p, 0),
    PB_FIELD( 18, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, r, q, 0),
    PB_FIELD( 19, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, s, r, 0),
    PB_FIELD( 20, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, t, s, 0),
    PB_FIELD( 21, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, u, t, 0),
    PB_FIELD( 22, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, v, u, 0),
    PB_FIELD( 23, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, w, v, 0),
    PB_FIELD( 24, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, x, w, 0),
    PB_FIELD( 25, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, y, x, 0),
    PB_FIELD( 26, INT32   , OPTIONAL, STATIC  , OTHER, TestMessage, z, y, 0),
    PB_LAST_FIELD
};


/* @@protoc_insertion_point(eof) */
